version: '3.8'

services:
  f5-translator:
    build: .
    container_name: f5-translator-app
    ports:
      - "5000:5000"
    volumes:
      # 持久化数据目录
      - ./data:/app/data
      # 持久化日志目录
      - ./logs:/app/logs
      # 配置文件（如果需要）
      - ./core/config.py:/app/core/config.py:ro
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - f5-network

  # 如果需要数据库，可以添加以下服务
  # redis:
  #   image: redis:7-alpine
  #   container_name: f5-redis
  #   restart: unless-stopped
  #   networks:
  #     - f5-network

networks:
  f5-network:
    driver: bridge

volumes:
  data:
  logs: 